# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      python3 -m venv venv
      . venv/bin/activate
      export PIP_USER=false
      pip install -r requirements.txt
    command: echo 'start script'
