# Generated by Django 3.2.8 on 2021-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pain_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
