# Generated by Django 3.2.8 on 2021-11-06 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pain',
            name='labels',
            field=models.ManyToManyField(related_name='pain', to='api.Label'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
