# Generated by Django 3.2.8 on 2021-11-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pain',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='pain', to='api.Label'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='pain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='api.pain'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
