# Generated by Django 3.2.8 on 2021-11-13 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211109_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
